apiVersion: v1
kind: Service
metadata:
  name: policyservice
  labels:
    app: policyservice
spec:
  ports:
  - port: 80
    name: http
  selector:
    app: policyapi2024
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: policyapi2024
spec:
  selector:

    matchLabels:

      app: policyapi2024
  replicas: 1
  template:
    metadata:
      labels:
        app: policyapi2024
        version: v1
    spec:
      containers:
      - name: policyapi2024
        image: eswaribala/novacmstrainingbatch2:policyapiv1
        
        ports:
        - containerPort: 80
        env:

            - name: ASPNETCORE_ENVIRONMENT

              value: DEVELOPMENT

            - name: SQLSERVER_CONNECTIONSTRING1

              value: "Server=host.docker.internal,1403;Database=PolicyDbBatch2;User ID=sa;Password=Vignesh@95;MultipleActiveResultSets=true;TrustServerCertificate=true;"
            