version: "3"

services:
  app:
    build: .
    command: npm run dev
    ports:
      - "3005:3005"
    #volumes:
    #  - .:/usr/app
    depends_on:
      - "mongo"
    networks:
      - backend

  mongo:
    container_name: "mongo-node"
    #platform: linux/amd64
    image: mongo:4.4.14
    ports:
      - "27017:27017"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
    networks:
      - backend
  prometheus:
    image: prom/prometheus
    restart: always
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - backend

  grafana:
      image: grafana/grafana
      #command:
      environment:
        - GF_SECURITY_ADMIN_PASSWORD=P@ssw0rd
      restart: always
      ports:
        - 3000:3000
      networks:
        - backend

networks:
  backend:
    driver: bridge
